#log-file-path: E:/file/water-food/log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///survey?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    # 数据库用户名&密码：
    username: root
    password: wuyuanjian0


server:
  port: 80


file:
  path:
    from: \tuchuang\
    loacl: C:\Users\Rache\Documents\file

